import localFont from "next/font/local";

import Header from "../components/common/header";
import Footer from "../components/common/footer";
import "./globals.css";
import "./slick-slider.css";
import "./lightbox.css";

const vazirFont = localFont({ src: "../assets/fonts/Dana-Regular.woff2" });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html dir="rtl" lang="fa">
			<body className={`${vazirFont.className} antialiased`}>
				<Header />
				{children}
				<Footer />
				<div id="portal-container" />
			</body>
		</html>
	);
}
